# Generated by Django 5.0.1 on 2025-03-20 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_bot", "0002_conversation_title_alter_conversation_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="bot_response",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="user_input",
        ),
        migrations.AlterField(
            model_name="conversation",
            name="title",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_input", models.TextField()),
                ("bot_response", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_set",
                        to="chat_bot.conversation",
                    ),
                ),
            ],
        ),
    ]
