# Generated by Django 5.0.1 on 2025-03-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_bot", "0003_remove_conversation_bot_response_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="bot_response",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conversation",
            name="user_input",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="conversation",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="Chat",
        ),
    ]
